### PR TITLE
NetManager allows mutiple default interfaces

### LINKED ISSUE #200: NetManager failing on devices with multiple default routes
## Short
When starting the NodeEngine (thus the NetManager) on a device that has several default routes - e.g., it has multiple network interfaces. The NetManager component seems to fail, and no service can be deployed.

Image

My main reason for opening this issue is that I needed a while until I looked into the source code of orchestra-net to know that the root cause was multiple default routes. - My setup was a vanilla Ubuntu with multiple network interfaces - let's imagine a new Oakestra user has the same issue ...

## Proposal 
I noticed this when I started using a new mini-pc where I have an ethernet cable connected as well as a wifi connection:
```
OS: Ubuntu 24.04.1 LTS x86_64 
Host: AK10 
Kernel: 6.8.0-52-generic 
Packages: 854 (dpkg) 
Shell: bash 5.2.21 
Terminal: node 
CPU: Intel N100 (4) @ 3.400GHz 
GPU: Intel Alder Lake-N [UHD Graphics] 
Memory: 1251MiB / 15700MiB 
```
My ips and routes:
```
(base) alex@piccolo:~/oakestra_main_repo/oakestra$ ip -4 -br a
lo               UNKNOWN        127.0.0.1/8 
enp1s0           UP             192.168.178.74/24 metric 100 
wlo1             UP             192.168.178.73/24 metric 600 
br-13d3fe2349d6  DOWN           172.18.0.1/16 
docker0          UP             172.17.0.1/16 
br-470373582bdb  UP             172.19.0.1/16 

(base) alex@piccolo:~/oakestra_main_repo/oakestra$ ip r
default via 192.168.178.1 dev enp1s0 proto dhcp src 192.168.178.74 metric 100 
default via 192.168.178.1 dev wlo1 proto dhcp src 192.168.178.73 metric 600

172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
172.18.0.0/16 dev br-13d3fe2349d6 proto kernel scope link src 172.18.0.1 linkdown 
172.19.0.0/16 dev br-470373582bdb proto kernel scope link src 172.19.0.1 
192.168.178.0/24 dev enp1s0 proto kernel scope link src 192.168.178.74 metric 100 
192.168.178.0/24 dev wlo1 proto kernel scope link src 192.168.178.73 metric 600 
192.168.178.1 dev enp1s0 proto dhcp scope link src 192.168.178.74 metric 100 
192.168.178.1 dev wlo1 proto dhcp scope link src 192.168.178.73 metric 600 
```

This is roughly what the NodeEngine logs show after start:
```
(base) alex@piccolo:~/oakestra_main_repo/oakestra$ sudo NodeEngine -a 192.168.178.74
NodeEngine started  🟢
INFO-2025/02/13 16:23:57 nodeengined.go:49: Startup addon: FLOps-learner
INFO-2025/02/13 16:23:57 FLOps.go:12: Starting FLOps Data Manager
INFO-2025/02/13 16:23:58 FLOps.go:60: FLOps Data Manager container started successfully.
INFO-2025/02/13 16:23:58 nodeengined.go:49: Startup addon: image-builder
INFO-2025/02/13 16:23:58 nodeengined.go:98: INIT: Starting handshake with cluster orchestrator 192.168.178.74:10100
INFO-2025/02/13 16:23:58 nodeengined.go:100: Node Statistics: 
__________________
INFO-2025/02/13 16:23:58 nodeengined.go:101: CPU Cores: 4
INFO-2025/02/13 16:23:58 nodeengined.go:102: CPU Usage: 0.940000
INFO-2025/02/13 16:23:58 nodeengined.go:103: Mem Usage: 14.835423
INFO-2025/02/13 16:23:58 nodeengined.go:104: GPU Driver: -
INFO-2025/02/13 16:23:58 nodeengined.go:105: 
________________
ERROR-2025/02/13 16:23:58 ClusterManagerRequests.go:28: Handshake failed, Post "http://192.168.178.74:10100/api/node/register": dial tcp 192.168.178.74:10100: connect: connection refused
```
or
`ERROR-2025/02/13 16:40:06 nodeengined.go:76: Error registering to NetManager: Post "http://localhost:0/register": EOF`

---

I "hacked" a fix by adding this file:
```
# /usr/local/bin/alex_cleanup_default_routes
sudo ip route del default via 192.168.178.1 dev wlo1 proto dhcp src 192.168.178.73 metric 600
```
and this crontab change: `sudo crontab -e`
```
@reboot /usr/local/bin/alex_cleanup_default_routes
```

## Solution 
I think the issue can be found here in `node-net-manager/network/NetUtils.go`:

Image

One possible (AFAIK) fix is to just take the first default route - maybe?

## Status
Looking for feedback.
This issue is not urgent (I am quite happy with my workaround) - I just wanted to write that down.

## Checklist
- [x] Discussed
- [ ] Solved
- [ ] Tested

### PR DESCRIPTION
**Pull request by Mjaethers**
Fixes #200.

The NetManager can now use any default interface instead of being restricted to just one.
When configuring a connection it will cross-reference it with a list of default interface names.

Tested on an RPi4, which will also configure two default routes when a wifi and an ethernet connection is available.

### CODE REVIEW

**Comment by Mjaethers** [comment]
Once the NetManager is running and one of the interfaces becomes unavailable (e.g. the wifi gets dropped) it will not hotswap to the other one. Currently looking into solutions but ideas and suggestions are welcome

**Comment by smnzlnsk** [comment]
Did you check for consistency in the setup process? Does it always return the same default interface when booting up? 
Because this is a make-or-break kind of change for the setup.

Additionally, this is not an easy problem, as setups can vary immensely from site to site. And also, policy-based routing is a thing.

Having two default routes on a machine is a bomb waiting to explode, and cannot be generalised and solved from inside the network manager itself. This needs input from the person wanting to start up the network manager. 

More specifically: We cannot assume, that both default routes lead to the same network in the background. This will not work, as this assumption in most cases does not hold true for the problem at hand. If I have two default routes, because my ethernet is connected to a local router, doing DHCP and setting up the default route inherently, in addition to my WiFi being connected to, let's say, eduroam, how can you consistently tell, which default interface to use in order to reach the internet?

All this needs to be considered when tackling the issue, and usually are handled by custom routes on such machines or as I already mentioned, policy-based routing, set up by the host admin.

I think at this point the quick and easy solution would be for the person deploying the network manager to define the default interface to use, as we cannot and never will be able to solve this in a one-size-fits-all type of way at startup. I personally would propose to add a field in the network manager configuration that holds the string of the default interface to use and be done with it.


Just my two cents.

**Comment by Mjaethers** [comment]
Regarding consistency: It always returns eth0 when available, even if I manually change the weights to prioritise wlan0. I think it goes through them in alphabetical order.

As for having multiple default routes I think the solution of specifying the default route in the configuration file adds a lot of unwanted user complexity, especially now that the Network Manager basically works out of the box.
I suppose this value could be set to zero on default, and only if it's set does the Network Manager not fail if there are multiple default routes in the system. Otherwise it should fail and prompt the user to specify this field.

Another option to consider might be attempting to reach some endpoint (e.g. the cluster) with both interfaces and basing our choice of interface of that.

What do you think?

**Comment by smnzlnsk** [comment]
After thorough discussion it it probably best to make a set of changes:
- the configuration hierarchy for this problem should be: first read from the config file, if a field for the default interface is set. If not, check if a flag is set at startup, pointing to the string of the default network interface. If none of the previous cases are true, expect only one default route to be present. If not, crash with a warning, that actions need to be taken (like, start with the flag, giving us the default interface to be used, or set the field in the configuration)
- with the get started script it is advisable to include a new field in the config that is created at invocation, which is set by retrieving the current default interface. In the case multiple default routes are present, we need to ask the developer, which one he wants to choose, in order to proceed with the setup. We must not allow him to oversee this, as this might break and discourage people of using the platform, if the resulting setup fails.
- In case someone does not use the get-started, but a new version of the network manager, in the case of multiple default routes being present (and missing configuration, as required above), the network manager will fail with the error, that multiple routes are present - restart with flag pointing to default interface to be used. 

Generally, if two default routes are present, we need to make the deployer aware, that their setup may cause issues and for everyone's sake, it will be up to him to resolve this issue (because he is also the only one that will be able to solve it - we do not know what his setup looks like).

**Comment by Mjaethers** [comment]
As far as I can tell the netmanager config files are no longer being pulled in the getstarted script. All NodeEngine and NetManager configuration happens in the install-worker script. Therefore we don't need to make any changes to the scripts and changing the config/netcfg.json file here should suffice.

I need to run some tests and I'll mark it ready for review once that's done

**Comment by Mjaethers** [comment]
I think an open question is where to document this. As far as I can tell we only discuss the usage of the NetManager in the Getting started section, but this seems very advanced/niche for that part of the documentation.

File: node-net-manager/cmd/root.go [hunk 1]
```diff
@@ -34,20 +36,26 @@ func Execute() error {
 
 func init() {
 	cfgFile = "/etc/netmanager/netcfg.json"
+	rootCmd.Flags().StringVarP(&defaultIface, "defaultInterface", "i", "", "Sets the default interface (only relevant if the system has more than one)")
```
Comment (giobart) [inline node-net-manager/cmd/root.go]: what if we keep this only as part of the config file? I think it is weird to have only this option here but not the others. What do you think?

File: node-net-manager/network/NetUtils.go [hunk 2]
```diff
@@ -16,12 +17,12 @@ import (
 func GetLocalIPandIface() (string, string) {
```
Comment (giobart) [inline node-net-manager/network/NetUtils.go:17]: while at it... what if we change this to (string,error)?

File: node-net-manager/network/NetUtils.go [hunk 3]
```diff
@@ -89,20 +90,38 @@ func defaultRoute() (*netlink.Link, error) {
 	if err != nil {
 		return nil, fmt.Errorf("error retrieving default route %w", err)
 	}
-	if n := len(routes); n > 1 {
-		return nil, fmt.Errorf("found more than one default net routes (%d)", n)
-	}
 
 	if len(routes) == 0 {
 		return nil, nil
```
Comment (giobart) [inline node-net-manager/network/NetUtils.go:95]: can this be a good spot for a panic?

File: node-net-manager/network/NetUtils.go [hunk 4]
```diff
@@ -89,20 +90,38 @@ func defaultRoute() (*netlink.Link, error) {
...
 	}
 
+	if n := len(routes); n > 1 {
+		if model.NetConfig.DefaultInterface == "" {
+			return nil, fmt.Errorf("found more than one default net routes (%d). Specify the required default interface on startup with the -i flag", n)
```
Comment (giobart) [inline node-net-manager/network/NetUtils.go]: if -i flag is removed from startup, then this should point to the config file

**Review by giobart — CHANGES_REQUESTED** [review]

File: node-net-manager/cmd/root.go (hunk 1 above)
Comment (Mjaethers) [reply node-net-manager/cmd/root.go]: I think it's cleaner, but this does mean that anybody who had already installed the NetManager has to reinstall or manually add the field in the config file.
I guess this all raises a larger issue around updating Oakestra components.

I'll make the changes

File: node-net-manager/network/NetUtils.go (hunk 2 above)
Comment (Mjaethers) [reply node-net-manager/network/NetUtils.go:17]: I don't think this makes sense, as the second return value is the interface. It being non-null doesn't indicate an error, quite the opposite, it' supposed to return both values.

File: node-net-manager/network/NetUtils.go (hunk 3 above)
Comment (Mjaethers) [reply node-net-manager/network/NetUtils.go:95]: I think there's no need. This function returns with an error here and the calling function will write one more line to the logs and then immediately panic

**Comment by giobart** [comment]
all good for me, I piggybacked a python update for the root and cluster base images hoping it solves the build issues we have in develop. Running the test pipeline on this branch right now, if everything shows up green we can proceed with the merge.

**Review by giobart — APPROVED** [review]

**Comment by giobart** [comment]
Finally pipeline turned all green :D Ready to merge
